

spring:
  datasource:
    url: jdbc:h2:file:~/data.sql
    username: username
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      
  sql:
    init:
      mode: always
         
  jpa:
    hibernate: 
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect  
    open-in-view: false
#   We need Hibernate to create our tables before inserting the data into them
    defer-datasource-initialization: true
    
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true  
               
  application:
    name: STUDENT-REST-APP
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      StudentEmailUnique: STUDENT_EMAIL_UNIQUE
      StudentContactUnique: STUDENT_CONTACT_UNIQUE
springdoc:
  pathsToMatch: /api/**
  
server:
  port: 8080
