
INSERT INTO STUDENT (ID, CONTACT, EMAIL, FIRSTNAME, LASTNAME)  VALUES(1, 1234567890,'mayur@test.com','Mayur','Bhosale');
INSERT INTO STUDENT (ID, CONTACT, EMAIL, FIRSTNAME, LASTNAME)  VALUES(2,1234567891,'laxman@test.com','Laxman','Devkate');
INSERT INTO STUDENT (ID, CONTACT, EMAIL, FIRSTNAME, LASTNAME)  VALUES(3,1234567892,'akash@test.com','Akash','Jadhav');
INSERT INTO STUDENT (ID, CONTACT, EMAIL, FIRSTNAME, LASTNAME)  VALUES(4,1234567893,'vaibhav@test.com','Vaibhav','Bane');
INSERT INTO STUDENT (ID, CONTACT, EMAIL, FIRSTNAME, LASTNAME)  VALUES(5,1234567894,'bhushan@test.com','Bhushan','Patil');
INSERT INTO STUDENT (ID, CONTACT, EMAIL, FIRSTNAME, LASTNAME)  VALUES(6,1234567895,'shyam@test.com','Shyam','Kadam');
INSERT INTO STUDENT (ID, CONTACT, EMAIL, FIRSTNAME, LASTNAME)  VALUES(7,1234567896,'nikhil@test.com','Nikhil','Mane');